# Updated for SwiftLint 0.27.0


# SwiftLint documentation
#
# A detailed description of all existing rules and their parameters can be found here:
# https://github.com/realm/SwiftLint/blob/master/Rules.md





included:
  # Path to application source code

excluded:
  # Lint only our code, not that of included pods
  - "${PWD}/build"
  - "${PWD}/Pods"
  - "${PWD}/**/*/R.generated.swift"


# -----------------------------------------------
# -------------------- Rules --------------------
# -----------------------------------------------


disabled_rules:
  - class_delegate_protocol
  - custom_rules
  - discarded_notification_center_observer
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - generic_type_name
  - large_tuple
  - inclusive_language
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - notification_center_detachment
  - object_literal
  - orphaned_doc_comment
  - private_over_fileprivate
  - protocol_property_accessors_order
  - quick_discouraged_call
  - trailing_newline
  - type_body_length

  
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
#  - convenience_type
  - discouraged_assert
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - fallthrough
  - fatal_error_message
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_hashing
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
#  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - reduce_into
  - single_test_class
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unowned_variable_capture
  - unused_capture_list
  - unused_control_flow_label
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
  - explicit_init
  - weak_delegate


# -------------------------------------------------
# -------------------- Options --------------------
# -------------------------------------------------


anyobject_protocol:
  severity: error


array_init:
  severity: error


attributes:
  severity: warning
  always_on_same_line:
    - "@objc"
    - "@IBAction"
    - "@IBInspectable"
    - "@IBOutlet"
    - "@NSManaged"
  always_on_line_above:
    - "@objcMembers"
    - "@IBDesignable"



block_based_kvo:
  severity: error


# class_delegate_protocol:
#   severity: error

closure_body_length:
  warning: 30
  error: 50


closing_brace:
  severity: error


closure_end_indentation:
  severity: error


closure_parameter_position:
  severity: error


closure_spacing:
  severity: error

collection_alignment:
  severity: warning


colon:
  severity: error
  flexible_right_spacing: false
  apply_to_dictionaries: true


comma:
  severity: error


compiler_protocol_init:
  severity: error


conditional_returns_on_newline:
  severity: error
  if_only: true


contains_over_first_not_nil:
  severity: error


control_statement:
  severity: error
  
#convenience_type:
#  severity: warning

# discouraged_object_literal:
#   severity: warning

discouraged_optional_boolean:
  severity: warning

discouraged_optional_collection:
  severity: warning

duplicate_imports:
  severity: error


# custom_rules:
#   severity: warning


cyclomatic_complexity:
  # Community Standard
  warning: 10
  # Community Standard
  error: 20
  # Aktiv, da Regelverstöße in Switches erfahrungsgemäß oft False Positives sind
  ignores_case_statements: true


discouraged_direct_init:
  severity: error
  types:
    - Bundle
    - UIDevice
    - UIScreen
    - UIApplication


dynamic_inline:
  severity: error


empty_count:
  severity: error

empty_string:
  severity: error


empty_enum_arguments:
  severity: error


empty_parameters:
  severity: error


empty_parentheses_with_trailing_closure:
  severity: error

empty_xctest_method:
  severity: error

# explicit_acl:
#   severity: warning


# explicit_enum_raw_value:
#   severity: warning


# explicit_init:
#   severity: warning


# explicit_top_level_acl:
#   severity: warning


# explicit_type_interface:
#   severity: warning


# extension_access_modifier:
#   severity: warning


fallthrough:
  severity: error


fatal_error_message:
  severity: error


# file_header:
#   severity: warning
#   forbidden_pattern:
#   forbidden_string:
#   required_pattern:
#   required_string:


file_length:
  warning: 1000
  error: 1000
  ignore_comment_only_lines: false

# file_name:
#   severity: warning
#   excluded: [main.swift]


first_where:
  severity: error


for_where:
  severity: error


force_cast:
  severity: error


force_try:
  severity: error


force_unwrapping:
  severity: error


function_body_length:
  warning: 40
  error: 40

function_default_parameter_at_end:
  severity: warning


function_parameter_count:
  warning: 5
  error: 5


# generic_type_name:
#   min_length:
#     warning: 0
#   max_length:
#     warning: 100
#   # Validiert, dass Typen mit Großbuchstaben beginnen (Name der Option is irreführend)
#   validates_start_with_lowercase: true
#   #allowed_symbols:
#   #excluded:


identical_operands:
  severity: warning


identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 64
  validates_start_with_lowercase: true
  # allowed_symbols:
  excluded:
    - id

inert_defer:
  severity: error


implicit_getter:
  severity: error


implicit_return:
  severity: error


implicitly_unwrapped_optional:
  severity: error
  mode: "all_except_iboutlets" # Values: all | all_except_iboutlets


is_disjoint:
  severity: error


joined_default_parameter:
  severity: error


# large_tuple:
#   warning: 4

last_where:
  severity: error


leading_whitespace:
  severity: warning


legacy_cggeometry_functions:
  severity: error


# Konfiguriert als Fehler, weil veraltet.
legacy_constant:
  severity: error


legacy_constructor:
  severity: error

legacy_hashing:
  severity: error


legacy_nsgeometry_functions:
  severity: error

legacy_random:
  severity: error


let_var_whitespace:
  severity: error


line_length:
  warning: 250
  error: 350
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true


literal_expression_end_indentation:
  severity: error


mark:
  severity: warning

#missing_docs:
#  warning: [open, public, internal]


multiline_arguments:
  severity: error
  first_argument_location: "any_line" # Values: any_line | same_line | next_line

multiline_arguments_brackets:
  severity: warning

multiline_function_chains:
  severity: warning

multiline_literal_brackets:
  severity: warning


multiline_parameters:
  severity: error

multiline_parameters_brackets:
  severity: warning


# multiple_closures_with_trailing_closure:
#   severity: warning


nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3



nslocalizedstring_key:
  severity: warning


# object_literal:
#   severity: warning
#   image_literal: true
#   color_literal: true


opening_brace:
  severity: error


operator_usage_whitespace:
  severity: error


operator_whitespace:
  severity: error

# override_in_extension:
#   severity: warning


overridden_super_call:
  severity: error
  # excluded:
  # included:


pattern_matching_keywords:
  severity: error

# prefixed_toplevel_constant:
#   severity: warning
#   only_private: false

private_action:
  severity: error


private_outlet:
  severity: error
  # Alternativ zu private reicht ein privater Setter
  allow_private_set: true


# private_over_fileprivate:
#   severity: warning
#   # Extensions innerhalb einer Datei werden ebenfalls berücksichtigt
#   validate_extensions: true


private_unit_test:
  severity: warning
  regex: "XCTestCase"


prohibited_super_call:
  severity: error
  # excluded:
  # included:


# protocol_property_accessors_order:
#   severity: warning

# BISHER KEIN INDIKATOR
# quick_discouraged_call:
#   severity: warning


redundant_discardable_let:
  severity: error

redundant_objc_attribute:
  severity: error


# Deaktiviert, da es zumindest ein Szenario gibt, in dem man es tun würde und dieser Fall der Regelfall sein dürfte (doppelte Optionals).
# redundant_nil_coalescing:
#   severity: warning


redundant_optional_initialization:
  severity: error

# redundant_set_access_control:
#   severity: warning


redundant_string_enum_value:
  severity: warning


redundant_void_return:
  severity: error

# required_enum_case:
#   severity: warning


return_arrow_whitespace:
  severity: error


shorthand_operator:
  severity: error


single_test_class:
  severity: error

sorted_first_last:
  severity: error


# sorted_imports:
#   severity: warning


statement_position:
  severity: error
  # Ein Zeilenumbruch vor dem else ("uncuddled") wird nicht erlaubt
  statement_mode: default # Values: default | uncuddled_else

static_operator:
  severity: error


# strict_fileprivate:
#   severity: warning


superfluous_disable_command:
  severity: error


switch_case_alignment:
  severity: error
  indented_cases: false


switch_case_on_newline:
  severity: error


syntactic_sugar:
  severity: error


# Konfiguriert als Warnung, da ein TODO mit Verweis auf ein Ticket (!) sinnvoll sein kann.
todo:
  severity: warning

toggle_bool:
  severity: warning


trailing_closure:
  severity: error


trailing_comma:
  severity: error
  # Hinter dem letzten Element in Array und Dictionary Literalen soll kein Komma stehen
  mandatory_comma: false


# trailing_newline:
#   severity: warning


trailing_semicolon:
  severity: error


# Xcode kann Trailing Whitespace automatisch trimmen, siehe "Preferences -> Text Editing -> While editing: Automatically trim trailing whitespace" (Xcode 9)
trailing_whitespace:
  severity: warning
  ignores_empty_lines: true
  ignores_comments: true


# Deaktiviert, da file_length und function_body_length geeigneter erscheinen.
# type_body_length:
#   warning: 1000
#   error: 1000


type_name:
  min_length:
    warning: 3
  max_length:
    warning: 1000
  # Validiert, dass Typen mit Großbuchstaben beginnen (Name der Option is irreführend)
  validates_start_with_lowercase: true
  # allowed_symbols:
  excluded:
    - "ID"
    - "Id"

# unavailable_function:
#   severity: warning


unneeded_break_in_switch:
  severity: error


unneeded_parentheses_in_closure_argument:
  severity: error

untyped_error_in_catch:
  severity: error


unused_closure_parameter:
  severity: error

unused_control_flow_label:
  severity: warning


unused_enumerated:
  severity: error


unused_optional_binding:
  severity: error
  ignore_optional_try: false


valid_ibinspectable:
  severity: warning


vertical_parameter_alignment:
  severity: error


vertical_parameter_alignment_on_call:
  severity: error


vertical_whitespace:
  severity: error
  max_empty_lines: 2

vertical_whitespace_closing_braces:
  severity: warning


void_return:
  severity: error


weak_delegate:
  severity: error


# xctfail_message:
#   severity: warning

yoda_condition:
  severity: warning
